config/routes.rb
Rails.application.routes.draw do

  resources :sessions
  resources :users
  resources :posts

  root 'static_pages#home'

  get '/about' => 'static_pages#about'

  get 'signup', to: 'users#new', as: 'signup'
  get 'signin', to: 'sessions#new', as: 'signin'
  get 'signout', to: 'sessions#destroy', as: 'signout'
end

app/models/post.rb
class Post
  include MongoMapper::Document

  key :title, String, :required => true
  key :content, String, :required => true

  timestamps!
end

app/models/user.rb
require 'bcrypt'

class User
  include MongoMapper::Document
  include ActiveModel::SecurePassword
  include BCrypt
  has_secure_password

  key :password_digest,       String
  key :email,                 String
  key :password_confirmation, String

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authorize
    redirect_to signin_url if current_user.nil?
    flash[:alert] = "Not authorized"
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authorize, only: [:edit, :update, :new, :create, :destroy]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)

    if @post.save
      flash[:success] = "Post successfully created."
      redirect_to post_path(@post)
    else
      render :action => "new"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.attributes = post_params

    if @post.save
      redirect_to @post
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Signed in!"
      redirect_to root_url
    else
      flash[:error] = "Email or password is invalid."
      redirect_to :back
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Signed out!"
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Thank you for signing up!"
      redirect_to root_url
    else
      render :action => "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert alert-success"
      when :error
        "alert alert-error"
      when :alert
        "alert alert-block"
      when :notice
        "alert alert-info"
      else
        flash_type.to_s
    end
  end

end

app/helpers/minimal_form_helper.rb
require "minimal_form_builder"
module MinimalFormHelper
  def minimal_form_for(object, *args, &block)
    options = args.extract_options!
    simple_form_for(object, *(args << options.merge(:builder => MinimalFormBuilder)), &block)
  end

  def minimal_fields_for(*args, &block)
    options = args.extract_options!
    simple_fields_for(*(args << options.merge(:builder => MinimalFormBuilder)), &block)
  end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_header.html.haml
%nav.navbar.navbar-static-top.navbar-default{role: "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: root_path} Some Blog
    .collapse.navbar-collapse.navbar-ex1-collapse
      - if current_user
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign out", session_path("current"), method: "delete"
      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign Up", signup_path
          %li= link_to "Sign In", signin_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Some Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<%= render "layouts/header" %>
<div class="container">
  <%= render partial: "layouts/flash_messages", flash: flash %>
  <%= yield %>
</div>
</body>
</html>

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation{style: "margin-bottom:60px;"}
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg
  = f.text_field :title, placeholder: "Title"
  %br
  %br
  = f.text_area(:content, cols: 100, rows: 10, placeholder: "Content")
  %br
  = f.button :submit, class: "btn-primary btn-lg"

app/views/posts/edit.html.haml
.jumbotron
  %h1 Edit post
  = render "posts/form"
  %br
  %h4= link_to "Go back", :back

app/views/posts/index.html.haml
.jumbotron
  %h1 Posts
  - if @posts.empty?
    %h3 No posts to show you right now.
  - else
    %table.table
      %tbody
        %tr
          %th Title
          %th Date Created
          %th
          %th
        - @posts.each do |post|
          %tr
            %td= link_to post.title, post_path(post)
            %td= post.created_at.strftime("%-m/%-d/%Y")
            %td= link_to "Edit post", edit_post_path(post)
            %td= link_to "Delete post", post_path(post), method: :delete

    = link_to "New post", new_post_path, class: "btn btn-primary btn-lg"

app/views/posts/new.html.haml
.jumbotron
  %h1 New blog post
  %br
  = render "posts/form"
  %br
  %h4= link_to "Go back", :back

app/views/posts/show.html.haml
.jumbotron
  %h1= @post.title
  %p= @post.content
  = link_to "All posts", posts_path

app/views/static_pages/about.html.haml
%h1 About
%p Some stuff

app/views/static_pages/home.html.haml
.jumbotron.center
  %h1 Some Blog
  %p
    = link_to 'View posts', posts_path, class: "btn btn-default btn-lg"
    = link_to 'New post', new_post_path, class: "btn btn-primary btn-lg"

app/views/users/new.html.haml
.jumbotron.center
  %h1 Sign Up
  = minimal_form_for @user do |f|
    - if @user.errors.any?
      .error-messages
        %h2 Form is invalid
        %ul
          - @user.errors.full_messages.each do |message|
            %li= message
    .field
      = f.input :email
    %br
    .field
      = f.input :password
    %br
    .field
      = f.input :password_confirmation
    %br
    .actions
      = f.submit "Sign Up", class: "btn btn-primary btn-lg"